# Generated by Django 5.0.4 on 2024-05-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=254795821140, max_length=15),
            preserve_default=False,
        ),
    ]
